//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaipaShop.EndPoints.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaipaShop.EndPoints.Api.Resources.SharedResource.en", typeof(SharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not a valid credit card number..
        /// </summary>
        internal static string CreditCardValidator {
            get {
                return ResourceManager.GetString("CreditCardValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not a valid email address..
        /// </summary>
        internal static string EmailValidator {
            get {
                return ResourceManager.GetString("EmailValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be empty..
        /// </summary>
        internal static string EmptyValidator {
            get {
                return ResourceManager.GetString("EmptyValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; has a range of values which does not include &apos;{PropertyValue}&apos;..
        /// </summary>
        internal static string EnumValidator {
            get {
                return ResourceManager.GetString("EnumValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be equal to &apos;{ComparisonValue}&apos;..
        /// </summary>
        internal static string EqualValidator {
            get {
                return ResourceManager.GetString("EqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be {MaxLength} characters in length..
        /// </summary>
        internal static string ExactLengthValidator {
            get {
                return ResourceManager.GetString("ExactLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be between {From} and {To} (exclusive)..
        /// </summary>
        internal static string ExclusiveBetweenValidator {
            get {
                return ResourceManager.GetString("ExclusiveBetweenValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be between {From} and {To}..
        /// </summary>
        internal static string InclusiveBetweenValidator {
            get {
                return ResourceManager.GetString("InclusiveBetweenValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Is Invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Is Required.
        /// </summary>
        internal static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be between {MinLength} and {MaxLength} characters. You entered {TotalLength} characters..
        /// </summary>
        internal static string LengthValidator {
            get {
                return ResourceManager.GetString("LengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be less than or equal to {MaxLength} characters. You entered {TotalLength} characters..
        /// </summary>
        internal static string MaximumLengthValidator {
            get {
                return ResourceManager.GetString("MaximumLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be greater than or equal to {MinLength} characters. You entered {TotalLength} characters..
        /// </summary>
        internal static string MinimumLengthValidator {
            get {
                return ResourceManager.GetString("MinimumLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is required..
        /// </summary>
        internal static string NotEmptyValidator {
            get {
                return ResourceManager.GetString("NotEmptyValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must not be equal to &apos;{ComparisonValue}&apos;..
        /// </summary>
        internal static string NotEqualValidator {
            get {
                return ResourceManager.GetString("NotEqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must not be null..
        /// </summary>
        internal static string NotNullValidator {
            get {
                return ResourceManager.GetString("NotNullValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be null..
        /// </summary>
        internal static string NullValidator {
            get {
                return ResourceManager.GetString("NullValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Code.
        /// </summary>
        internal static string PersonnelCode {
            get {
                return ResourceManager.GetString("PersonnelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not in the correct format..
        /// </summary>
        internal static string RegularExpressionValidator {
            get {
                return ResourceManager.GetString("RegularExpressionValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must not be more than {ExpectedPrecision} digits in total, with allowance for {ExpectedScale} decimals. {Digits} digits and {ActualScale} decimals were found..
        /// </summary>
        internal static string ScalePrecisionValidator {
            get {
                return ResourceManager.GetString("ScalePrecisionValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} Has Entred Value {1}.
        /// </summary>
        internal static string TestWithParamsError {
            get {
                return ResourceManager.GetString("TestWithParamsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
